### PR TITLE
Development

### PR DESCRIPTION
**Pull request by n0542344**
Hi Bruno, 

awesome project (and video, and blog in general), thanks a lot for that. Finally an easily approachable way to get started with drake!

I just made some minor tweaks to the script (since I had some issues with loaded libraries) and reduced cv and sample_n to make the script faster for toying around.

If you want, feel free to adapt it as you want.

Best wishes, Alex (a life science PhD-student from Vienna)

### CODE REVIEW

**Comment by b-rodrigues** [comment]
thanks for the patch! has been merged

**Comment by n0542344** [comment]
Hi Bruno!


Sorry for posting that here but I'm a non-twitter, non-youtube-account
person and you don't have an email-address on your blog (or at least I
didn't find it).


I really like your videos a lot, but one of the things I'm really
fascined by (except the functional programming-stuff, which is obviously
awesome) is your way of using Emacs as an R-IDE.  That topic is
something with I'm thinking about since quite some time but, to be
honest, I never managed to transition.


I'd love to know

  * how you did your transition into Emacs (e.g. is that even possible if you aren't able to write at least some rudimentary Elisp) and
  * what your setup looks like (not just dotfiles and the packages you are using, also your workflow, e.g. if you are using Emacs to work on remote machines interactively).


If you have any suggestions on that topic I'd be very grateful!


Best wishes, Alex (a life science PhD-student from Vienna)

**Comment by b-rodrigues** [comment]
Hi, 

I'll be making a video about it this week, schedule allowing. You're not the first one to ask me questions about it.

**Comment by n0542344** [comment]
Dear Bruno!


On Mon, 2021-01-18 (w03) 14:21:50, Bruno Rodrigues wrote:
>I'll be making a video about it this week, schedule allowing.


That's awesome, thanks a lot!


>You're not the first one to ask me questions about it.


;)


I can image that this is very interesting for people who are a bit more
advanced in their data analysis/programming journey, especially those
being familiar with general GNU/Linux work.


I'm looking forward to it!


Best wishes, Alex

**Comment by b-rodrigues** [comment]
hello so it took longer than I anticipated

https://youtu.be/lerL043DWRg

but basically, I don't know how to write any elisp, I just use the ESS layer. I just added some keyboard shortcuts and that's basically it. 

For the work flow as such, I use targets, the successor of drake. I'll be making a video about it soon (I won't give a date this time)

**Comment by n0542344** [comment]
On Sat, 2021-03-13 (w10) 12:53:21, Bruno Rodrigues wrote:
>[...] https://youtu.be/lerL043DWRg


Thanks a lot - I already watched it last night (your blog and
youtube-channel are in my rss-feed).  And I took your video as an
opportunity to finally try out Emacs+ESS myself (and fought for maybe
half an hour until I realized that 

    (setq ess-eval-visibly 'nowait)


is necessary since if I don't include it my R-shell freezes).  But now
it works and I can transition my R-development to Emacs, thanks!


>[...] I just added some keyboard shortcuts and that's basically it.


Especially your inclusion of

    '(polymode poly-R poly-noweb poly-markdown)


as well as the

    (define-key ...
      (lambda ()
        (interactive)
        (insert " %>% ")
        ...
        ))


is cool, that's something I have to copy!


>For the work flow as such, I use targets, the successor of drake.


'targets' is also one of the things on my to-learn-list!


>I'll be making a video about it soon (I won't give a date this time)


;-)


By the way: one additional reason to use something else than RStudio:
Emacs + TRAMP (or for me until now: neovim +
vim-slime/repl.nvim/neoterm).  This allows you to perform the actual
computational workload on a remote machine while using your local IDE
(although I think this is available at the commercially available
RStudio-version).  Now I only need a way to get my plots and my 'View()'
onto my local machine while using TRAMP, than I can use it exactly the
same way!


Thanks again for the great video!

**Pull request merged**
